# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{connection_ninja}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Herring"]
  s.date = %q{2010-09-01}
  s.description = %q{Handle multiple Database conenctions with ActiveRecord Models}
  s.email = %q{chris.herring.iphone@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "MIT-License",
     "Manifest",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "connection_ninja.gemspec",
     "lib/connection_ninja.rb",
     "spec/connection_ninja_spec.rb",
     "spec/fixtures/models.rb",
     "spec/fixtures/structure.sql",
     "spec/spec_helper.rb",
     "spec/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/cherring/connection_ninja}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Handle multiple Database conenctions with ActiveRecord Models}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/fixtures/models.rb",
     "spec/connection_ninja_spec.rb",
     "spec/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.beta19"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0.beta19"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0.beta19"])
  end
end

